TaskQueueCore/UI/TaskQueueCore/Models/ErrorViewModel.cs
namespace TaskQueueCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TaskQueueCore/UI/TaskQueueCore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using TaskQueueCore.Models;

namespace TaskQueueCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TaskQueueCore/UI/TaskQueueCore/Controllers/TaskQueueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TaskQueueCore.Domain.DTO.TaskQueue;
using TaskQueueCore.Interfaces;

namespace TaskQueueCore.Controllers
{
    public class TaskQueueController : Controller
    {
        private readonly ITaskQueue _TaskQueue;

        public TaskQueueController([FromServices] ITaskQueue TaskQueue)
        {
            _TaskQueue = TaskQueue;
        }

        public IActionResult Index()
        {
            var allJobs = _TaskQueue.GetAllJob();
            return View(allJobs);
        }

        [HttpGet]
        public IActionResult AddEnqueue()
        {
            return View(new EnqueueDTO());
        }

        [HttpPost]
        public async Task<IActionResult> AddEnqueue(EnqueueDTO enqueueDTO)
        {
            string jobId = await _TaskQueue.AddEnqueueJobAsync(enqueueDTO);
            return Json(new { jobId = jobId });
        }


        [HttpGet]
        public IActionResult AddRecurring()
        {
            return View(new RecurringDTO());
        }

        [HttpPost]
        public async Task<IActionResult> AddRecurring(RecurringDTO recurringDTO)
        {
            string jobId = await _TaskQueue.AddRecurringJobAsync(recurringDTO);
            return Json(new { jobId = jobId });
        }

    }
}

TaskQueueCore/UI/TaskQueueCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TaskQueueCore/UI/TaskQueueCore/Views/Shared/Partial/_MainMenu.cshtml
<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse mm-dd">
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="TaskQueue" asp-action="Index">TaskQueue</a>
        </li>
        <li>
            <div class="dropdown show">
                <a class="btn btn-secondary dropdown-toggle text-dark mm-dd-link" role="button"
                   id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Загрузчик
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" asp-controller="TaskQueue" asp-action="Index">Index</a>
                    <a class="dropdown-item" asp-controller="TaskQueue" asp-action="AddEnqueue">Выполнить задачу</a>
                    <a class="dropdown-item" asp-controller="TaskQueue" asp-action="AddRecurring">Добавить задачу в расписание</a>
                </div>
            </div>
        </li>
    </ul>
</div>

TaskQueueCore/UI/TaskQueueCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskQueueCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/mainMenu.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskQueueCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <partial name="Partial/_MainMenu" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TaskQueueCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TaskQueueCore/UI/TaskQueueCore/Views/TaskQueue/AddEnqueue.cshtml
@model TaskQueueCore.Domain.DTO.TaskQueue.EnqueueDTO

@{
    ViewData["Title"] = "AddEnqueue";
}

<h1>AddEnqueue</h1>

<h4>EnqueueDTO</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddEnqueue">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CodeTask" class="control-label"></label>
                <input asp-for="CodeTask" class="form-control" />
                <span asp-validation-for="CodeTask" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AimDate" class="control-label"></label>
                <input asp-for="AimDate" class="form-control" />
                <span asp-validation-for="AimDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ObjId" class="control-label"></label>
                <input asp-for="ObjId" class="form-control" />
                <span asp-validation-for="ObjId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TaskQueueCore/UI/TaskQueueCore/Views/TaskQueue/AddRecurring.cshtml
@model TaskQueueCore.Domain.DTO.TaskQueue.RecurringDTO

@{
    ViewData["Title"] = "AddRecurring";
}

<h1>AddRecurring</h1>

<h4>RecurringDTO</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddRecurring">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CronExpression" class="control-label"></label>
                <input asp-for="CronExpression" class="form-control" />
                <span asp-validation-for="CronExpression" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodeTask" class="control-label"></label>
                <input asp-for="CodeTask" class="form-control" />
                <span asp-validation-for="CodeTask" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortNameJob" class="control-label"></label>
                <input asp-for="ShortNameJob" class="form-control" />
                <span asp-validation-for="ShortNameJob" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JobId" class="control-label"></label>
                <input asp-for="JobId" class="form-control" />
                <span asp-validation-for="JobId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Queue" class="control-label"></label>
                <input asp-for="Queue" class="form-control" />
                <span asp-validation-for="Queue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TaskQueueCore/UI/TaskQueueCore/Views/TaskQueue/Index.cshtml
@model IEnumerable<TaskQueueCore.Domain.DTO.TaskQueue.HfJobDTO>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CodeTask)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RunJob)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Method)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CodeTask)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JobId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RunJob)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Method)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>